### ISSUE TITLE
spy js plugin for webstorm crashed

### ISSUE THREAD

**Issue by vooolll** [spy-js/spy-js#39]
/usr/bin/node /home/vol/Software/WebStorm-135.1063/plugins/spy-js/server/spy.js --port=3546

fs.js:653
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory '/home/vol/tmp/spy-js-session114910-4658-1k2i8yo'
    at Object.fs.mkdirSync (fs.js:653:18)
    at Object.mkdirSync (/home/vol/Software/WebStorm-135.1063/plugins/spy-js/server/node_modules/temp/lib/temp.js:138:6)
    at Object.<anonymous> (/home/vol/Software/WebStorm-135.1063/plugins/spy-js/server/lib/sessionStore.js:8:171)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vol/Software/WebStorm-135.1063/plugins/spy-js/server/lib/session.js:8:306)

Process finished with exit code 8

**Comment by qt911025** [comment]
Can Spy-js be configured to specify another tmp folder name?

**Comment by ArtemGovorov** [comment]
Spy-js is using node.js os.tmpdir(), which returns:
```javascript
  if (isWindows) {
    return process.env.TEMP ||
           process.env.TMP ||
           (process.env.SystemRoot || process.env.windir) + '\\temp';
  } else {
    return process.env.TMPDIR ||
           process.env.TMP ||
           process.env.TEMP ||
           '/tmp';
  }
```
So you'd like to use another temp folder - just define one of these environment variables to be the folder you like.
