### ISSUE TITLE
spy-js failling when using Bluebird's promisifyAll on mongoose

### ISSUE THREAD

**Issue by mbellezi** [spy-js/spy-js#45]
The code:

var mongoose = require('mongoose');
var Promise = require("bluebird");
Promise.promisifyAll(mongoose);

Gives the error:

session (0vnqo): Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at Mongoose.connection (C:\Projetos\startup\node_modules\mongoose\lib\index.js:301:84)
    at promisifiableMethods (C:\Projetos\startup\node_modules\bluebird\js\main\promisify.js:291:28)
    at promisifyAll (C:\Projetos\startup\node_modules\bluebird\js\main\promisify.js:25:25)
    at Function.Promise.promisifyAll (C:\Projetos\startup\node_modules\bluebird\js\main\promisify.js:514:42)
    at Object.<anonymous> (C:\Projetos\startup\index.js:57:37)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

Using node alone or only the node debugger, there is no error.

**Comment by ArtemGovorov** [comment]
After a bit of investigation, it turned out to be an issue with JavaScript strict mode. Spy-js removes strict mode when instrumenting the code and one of the bluebird library checks is based on the strict mode presence, so instrumented code and the original one start to behave differently. I'll look into an option of not removing the strict mode when instrumenting JavaScript code. In a meantime, a simple workaround would be to mute the file causing the issue using ["Capture exclusions"](http://blog.jetbrains.com/webstorm/2014/04/spy-js-webstorm-secret-service/#settings). This way the file will not be instrumented and the code will be executed just the way it does execute using node alone.

![screen shot 2015-01-05 at 12 09 15 pm](https://cloud.githubusercontent.com/assets/979966/5608609/652f4756-94d5-11e4-8547-0bc227a0db4a.png)

**Comment by ArtemGovorov** [comment]
Fixed spy-js to preserve the strict mode.
