### ISSUE TITLE
Process.hrtime error

### ISSUE THREAD

**Issue by ludydoo** [spy-js/spy-js#48]
This happens when I run spy-js for node in Webstorm 9.0.3

Unhandled rejection TypeError: process.hrtime() only accepts an Array tuple.
    at TypeError (native)
    at EventEmitter._.extend._timeDiff (/Applications/WebStorm.app/Contents/plugins/spy-js/server/lib/tracerNode.js:8:12744)
    at EventEmitter._.extend._return (/Applications/WebStorm.app/Contents/plugins/spy-js/server/lib/tracerNode.js:8:14983)

**Comment by ArtemGovorov** [comment]
What version of node.js are you using?

**Comment by ludydoo** [comment]
```
ludovic:usr ludydoo$ /usr/local/bin/node -v
v0.12.0
```

**Comment by ArtemGovorov** [comment]
Can't reproduce it yet, is there a chance you could provide some small sample where the issue could be reproduced?

**Comment by ludydoo** [comment]
Hi,

I've uploaded the project here : http://ge.tt/7HInmjA2/v/0?c

**Comment by ArtemGovorov** [comment]
Hello, I have downloaded the project, but I can't reproduce the issue. I had to comment out a couple of things to get it working as it seems to need a DB or something. I can navigate events, stack trees, etc. Are there any particular steps I have to take to reproduce the issue?

![screen shot 2015-02-23 at 5 46 27 pm](https://cloud.githubusercontent.com/assets/979966/6324319/0c609a46-bb84-11e4-91af-812ae08e5587.png)

**Comment by ludydoo** [comment]
I am trying to develop my library « Affinity » which is an in-memory relational algebra library. 

If you look at the console do you see the error ?

**Comment by ludydoo** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/38968/6328836/64584d7a-bb39-11e4-9364-7774827aa52d.jpg)

**Comment by ArtemGovorov** [comment]
```
/usr/local/bin/node src/app.js
Adding new person to storage...
Added new person : 
{ name: 'Ludovic',
  birth: Sat Oct 10 1987 00:00:00 GMT+1000 (AEST),
  death: Sun Oct 10 2100 00:00:00 GMT+1000 (AEST),
  dead: false,
  id: 0 }
Finding the person in storage...
Unhandled rejection TypeError: undefined is not a function
    at /Users/artemgovorov/Downloads/webtec/src/infrastructure/affinityStorage.js:84:45
    at tryCatcher (/Users/artemgovorov/Downloads/webtec/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/Users/artemgovorov/Downloads/webtec/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/Users/artemgovorov/Downloads/webtec/node_modules/bluebird/js/main/promise.js:53:37)
    at Object.people.findById (/Users/artemgovorov/Downloads/webtec/src/infrastructure/affinityStorage.js:72:12)
    at /Users/artemgovorov/Downloads/webtec/src/app.js:28:31
    at tryCatcher (/Users/artemgovorov/Downloads/webtec/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/artemgovorov/Downloads/webtec/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/artemgovorov/Downloads/webtec/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/artemgovorov/Downloads/webtec/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/artemgovorov/Downloads/webtec/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/Users/artemgovorov/Downloads/webtec/node_modules/bluebird/js/main/async.js:89:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/artemgovorov/Downloads/webtec/node_modules/bluebird/js/main/async.js:14:14)
    at processImmediate [as _immediateCallback] (timers.js:321:17)

Process finished with exit code 0
```

The result of the call:
```
person = resultRelation.first().toObject();
```
is undefined.

What set up steps am I missing? I have downloaded the project, ran `npm install`. Do I need anything else?

**Comment by agross** [comment]
Try spy for Node.js with this repo: https://github.com/agross/assemble-custom-loader. Use `node_modules\assemble\bin\assemble.js` as the JavaScript file.

The output is as follows:
```
spy-js has started
session store: C:\Users\agross\AppData\Local\Temp\spy-js-session115128-42388-1fe4jnf
session (r6vj2): new session created: r6vj2
session (r6vj2): ----------- Starting traced application process (42388) -----------
[12:04:39] Using assemblefile D:\Users\agross\Downloads\assemble-custom-loader\assemblefile.js
[12:04:39] Starting 'default'...
[12:04:41] Reading source/data/C14-x.json
...
process.hrtime() only accepts an Array tuple.
TypeError: process.hrtime() only accepts an Array tuple.
    at TypeError (native)
    at EventEmitter._.extend._timeDiff (C:\Program Files (x86)\JetBrains\WebStorm 9.0.3\plugins\spy-js\server\lib\tracerNode.js:8:12744)
    at EventEmitter._.extend._return (C:\Program Files (x86)\JetBrains\WebStorm 9.0.3\plugins\spy-js\server\lib\tracerNode.js:8:14983)
    at bound (C:\Program Files (x86)\JetBrains\WebStorm 9.0.3\plugins\spy-js\server\node_modules\lodash\dist\lodash.underscore.js:419:19)
    at Function.forEach (D:\Users\agross\Downloads\assemble-custom-loader\node_modules\lodash\index.js:2470:434)
    at D:\Users\agross\Downloads\assemble-custom-loader\assemblefile.js:66:43
    at arrayEach (D:\Users\agross\Downloads\assemble-custom-loader\node_modules\lodash\index.js:6260:44)
    at Function.forEach (D:\Users\agross\Downloads\assemble-custom-loader\node_modules\lodash\index.js:2470:311)
    at Stream.<anonymous> (D:\Users\agross\Downloads\assemble-custom-loader\assemblefile.js:58:39)
    at Stream.stream.write (D:\Users\agross\Downloads\assemble-custom-loader\node_modules\event-stream\node_modules\through\index.js:76:41)
[12:04:51] D:\Users\agross\Downloads\assemble-custom-loader\dist\cards\Abyssal_Persecutor\index.html
...
```

**Comment by ArtemGovorov** [comment]
@agross @ludydoo got it this time with https://github.com/agross/assemble-custom-loader, thanks. The issue is fixed and will be out in one of the next EAP builds of WebStorm 10.
