### ISSUE TITLE
errors using babel register

### ISSUE THREAD

**Issue by amcdnl** [spy-js/spy-js#53]
When I use Babel's Register function ( https://babeljs.io/docs/usage/require/ ), when I startup my application I get the following:

session (eueib): ----------- Starting traced application process (7264) -----------
session (eueib): obj is not defined
ReferenceError: obj is not defined
    at Object.<anonymous> (C:\dev\swimlane\Node\node_modules\json5\lib\json5.js:808:58)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\dev\swimlane\Node\node_modules\babel-core\lib\transformation\file\options\option-manager.js:34:43)

**Comment by ArtemGovorov** [comment]
You may try [muting](http://blog.jetbrains.com/webstorm/2014/04/spy-js-webstorm-secret-service/#settings) all node modules or just the `node_modules\json5`.

**Comment by amcdnl** [comment]
Thanks for the hint; that got me further but still no dice.  Does it support node es6?  I get this now:

session (w4q7h): Unexpected token ,
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

which staces to this line:

const configs = { 
  developmentConfig: _dev.developmentConfig, 
  productionConfig: _prod.productionConfig };

**Comment by ArtemGovorov** [comment]
It should support ES6 (at least the most of it anyway), there may be an issue with the parsing library it uses. I suspect the error could be on a different line (because reported stacks are for the instrumented code, not for the original code). Try muting/excluding this particular file as well to see if the issue is in it.
